src/Entity/Appointments.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\AppointmentsRepository;

#[ORM\Entity(repositoryClass: AppointmentsRepository::class)]
class Appointments
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(cascade: ['persist'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cares $care = null;

    #[ORM\Column(nullable: false)]
    private ?int $user_id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(nullable: true)]
    private ?int $child_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCare(): ?Cares
    {
        return $this->care;
    }

    public function setCare(Cares $care): self
    {
        $this->care = $care;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getChildId(): ?int
    {
        return $this->child_id;
    }

    public function setChildId(?int $child_id): self
    {
        $this->child_id = $child_id;

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Entity\Trait\CreatedAtTrait;
use App\Repository\UsersRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
// #[UniqueEntity(fields: ['email'], message: 'Il y a déjà un compte avec cette adresse email.')]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    use CreatedAtTrait;

    // les annotations sont des attributs de php 8
    // clé primaire
    #[ORM\Id]
    // auto-increment
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(options: ['default' => "ROLE_PATIENT"])]
    private ?array $roles = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $password = null;

    #[ORM\Column(length: 100)]
    private ?string $firstname = null;

    #[ORM\Column(length: 100)]
    private ?string $lastname = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $birthday = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $address_number = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address_details = null;

    #[Assert\Regex(pattern: '/^[0-9]{5}$/', message: 'Le code postal doit comporter 5 chiffres.')]
    #[Assert\Length(min: 5, max: 5, exactMessage: 'Le code postal doit comporter 5 chiffres.')]
    #[ORM\Column(length: 5, nullable: true)]
    private ?string $zipcode = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $city = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $country = null;

    #[Assert\Regex(pattern: '/^[0-9]{9}$/', message: 'Le numéro de téléphone doit comporter 9 chiffres.')]
    #[ORM\Column(length: 10, nullable: true)]
    private ?string $home_phone = null;

    #[Assert\Regex(pattern: '/^[0-9]{9}$/', message: 'Le numéro de téléphone doit comporter 9 chiffres.')]
    #[ORM\Column(length: 10, nullable: true)]
    private ?string $cell_phone = null;

    #[ORM\Column]
    private ?bool $is_blocked = false;

    #[ORM\Column(type: 'boolean')]
    private $is_verified = false;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $resetToken;

    #[ORM\Column(nullable: true)]
    private ?int $user_ref = null;

    public function __construct()
    {
        // Pour le champ created_at, on ajoute la date du jour
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER

        $roles[] = 'ROLE_PATIENT';


        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getAddressNumber(): ?string
    {
        return $this->address_number;
    }

    public function setAddressNumber(string $address_number): self
    {
        $this->address_number = $address_number;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getAddressDetails(): ?string
    {
        return $this->address_details;
    }

    public function setAddressDetails(string $address_details): self
    {
        $this->address_details = $address_details;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }
    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getHomePhone(): ?string
    {
        return $this->home_phone;
    }

    public function setHomePhone(string $home_phone): self
    {
        $this->home_phone = $home_phone;

        return $this;
    }

    public function getCellPhone(): ?string
    {
        return $this->cell_phone;
    }

    public function setCellPhone(string $cell_phone): self
    {
        $this->cell_phone = $cell_phone;

        return $this;
    }

    public function isIsBlocked(): ?bool
    {
        return $this->is_blocked;
    }

    public function setIsBlocked(bool $is_blocked): self
    {
        $this->is_blocked = $is_blocked;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;
        return $this;
    }

    public function getIsverified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsverified(bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    public function __toString(): string
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function getUserRef(): ?int
    {
        return $this->user_ref;
    }

    public function setUserRef(?int $user_ref): self
    {
        $this->user_ref = $user_ref;

        return $this;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Form\RegistrationFormType;
use App\Form\ResetPasswordFormType;
use App\Repository\CaresRepository;
use App\Repository\UsersRepository;
use App\Repository\ChildsRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\AppointmentsRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

// On définit manuellement le nom de la route depuis laquelle on accèdera à toutes les méthodes de ce contrôleur
#[Route('/profil', name: 'profile_')]
class ProfileController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(AppointmentsRepository $appointmentsRepository, CaresRepository $caresRepository, UsersRepository $usersRepository, PaginatorInterface $paginator, Request $request): Response
    {
        // Je vérifie que l'utilisateur est connecté , sinon je le redirige vers la page de connexion
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }
        $user = $this->getUser();
        // Je récupère la date du jour
        $date = new \DateTime();
        //! TODO: Mystère à résoudre ma requête avec >= ne fonctionne pas !!! pour nextAppointments
        // Je retire 1 jour à la date du jour car bug avec la date du jour (le 01/06/2023 à 10h13 le bug n'est plus là)
        // $date->modify('-1 day');

        // Je vérifie si l'utilisateur a des enfants
        $childs = $usersRepository->findChildsByUser($user->getId(), '["ROLE_CHILD"]');

        // Je récupère l'historique des rendez-vous de l'utilisateur connecté, on affiche 5 rendez-vous par page
        $pagination = $paginator->paginate(
            $appointmentsRepository->paginationQueryAppointmentsUser($user->getId(), $date),
            // je recupère la page et par defaut je lui met la 1
            $request->query->get('page', 1),
            5
        );

        // Je récupère les rendez-vous à venir de l'utilisateur connecté
        $nextAppointments = $appointmentsRepository->findNextAppointmentByUser($user->getId(), $date);

        // Je récupère tous les soins
        $cares = $caresRepository->findAll();

        return $this->render('profile/index.html.twig', [
            'user' => $user,
            'pagination' => $pagination,
            'nextAppointments' => $nextAppointments,
            'cares' => $cares,
            'childs' => $childs,
        ]);
    }

    #[Route('/votre-profil', name: 'show')]
    public function show(UsersRepository $usersRepository): Response
    {
        // Je vérifie que l'utilisateur est connecté , sinon je le redirige vers la page de connexion
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }
        $user = $this->getUser();

        // Je vérifie si l'utilisateur a des enfants
        $childs = $usersRepository->findChildsByUser($user->getId(), '["ROLE_CHILD"]');
        // dd($childs);
        return $this->render('profile/show.html.twig', [
            'user' => $user,
            'childs' => $childs,
        ]);
    }

    #[Route('/votre-profil/modifier', name: 'edit')]
    public function update(Request $request, UsersRepository $usersRepository): Response
    {
        // Je vérifie que l'utilisateur est connecté , sinon je le redirige vers la page de connexion
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }
        $user = $this->getUser();
        // Je récupère le formulaire de modification de profil en réutilisant le formulaire d'inscription
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $usersRepository->update($user, true);
            $this->addFlash('success', 'Votre profil a bien été modifié.');

            return $this->redirectToRoute('profile_show');
        }

        return $this->render('profile/edit.html.twig', [
            'user' => $user,
            'userForm' => $form->createView(),
        ]);
    }

    #[Route('/votre-profil/changer-mot-de-passe', name: 'changePassword')]
    public function changePassword(
        Request $request,
        EntityManagerInterface $entityManager,
        UserPasswordHasherInterface $passwordHasher
    ): Response {
        // Je vérifie que l'utilisateur est connecté , sinon je le redirige vers la page de connexion
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }
        $user = $this->getUser();

        if ($user) {

            $form = $this->createForm(ResetPasswordFormType::class);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $user->setPassword(
                    $passwordHasher->hashPassword(
                        $user,
                        $form->get('password')->getData()
                    )
                );
                $entityManager->persist($user);
                $entityManager->flush();

                $this->addFlash('success', 'Mot de passe changé avec succès');
                return $this->redirectToRoute('profile_index');
            }

            return $this->render('security/reset_password.html.twig', [
                'passForm' => $form->createView(),
                'user' => $user
            ]);
        }
        $this->addFlash('danger', 'Jeton invalide');
        return $this->redirectToRoute('profile_index');
    }
}

templates/profile/edit.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
	<link rel="stylesheet" href="/assets/css/_partials/form.css">
{% endblock %}

{% block title %}Votre profil
{% endblock %}

{% block body %}
	<div class="container">
		<div class="content content">
			<h2>Modifier votre profil</h2>
			<div class="form_users-bg bg-white">
				<div class="form_users edit_user">
					{{ form_start(userForm) }}
					{{ form_row(userForm.firstname) }}
					{{ form_row(userForm.lastname) }}
					{{ form_row(userForm.birthday) }}
					{{ form_row(userForm.email) }}
					{# {{ form_row(userForm.home_phone) }} #}
					{{ form_row(userForm.cell_phone) }}
					{{ form_row(userForm.address) }}
					{{ form_row(userForm.zipcode) }}
					{{ form_row(userForm.city) }}
					<div class="hidden">
						{{ form_row(userForm.country) }}
						{{ form_row(userForm.RGPDConsent) }}
						{{ form_row(userForm.plainPassword, {label: 'Mot de passe'}) }}
					</div>
					<button type="submit" class="btn btn-inscription">Mettre à jour mon profil</button>
					{{ form_end(userForm) }}
				</div>
			</div>

		</div>
	</div>
{% endblock %}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
	<script src="/assets/js/profile.js" defer></script>
{% endblock %}

{% block title %}Espace patient
{% endblock %}

{% block body %}
	<div class="container">
		<div class="content">
			<h1>Espace patient</h1>
			<div class="profile_list_appointments">
				<h3>Votre prochain rendez-vous</h3>
				<ul>
					{% for appointment in nextAppointments %}
						<li>
							<div class="profile_list_appointment_care">
								{% for care in cares %}
									{% if care.id == appointment.care.id %}
										<span class="color_care" style="color:{{ care.color }}">
											<i class="fa-solid fa-circle"></i>
										</span>
										{% if care.id == 2 or care.id == 5 %}
											{% for child in childs %}
												{% if child.id == appointment.childId %}
													<span>{{ care.name }}</span>
													<span class="appointment-child next">pour
														<strong>
															{{ child.firstname }}
														</strong>
													</span>
												{% endif %}
											{% endfor %}
										{% else %}
											<span>{{ care.name }}</span>
										{% endif %}
									{% endif %}
								{% endfor %}
							</div>
							<div class="profile_list_appointment_date">
								<span>{{ appointment.date|dayName }}</span>
								<span>{{ appointment.date|date('d') }}</span>
								<span>{{ appointment.date|monthName }}</span>
								<span>{{ appointment.date|date('Y') }}</span>
								à
								<span>{{ appointment.date|date('H') }}</span>h<span>{{ appointment.date|date('i') }}</span>
							</div>
							{{ include('/appointments/_delete_form.html.twig') }}
						</li>
					{% else %}
						<li>
							<div class="profile_list_appointment_care empty_list">
								<span>Vous n'avez pas de prochain rendez-vous</span>
							</div>
						</li>
					{% endfor %}
				</ul>
				<h3>Historique de vos rendez-vous</h3>
				<ul>
					{% for appointment in pagination %}
						<li class="olds-appointments_item">
							{% for care in cares %}
								{% if care.id == appointment.care.id %}
									<span class="color_care" style="color:{{ care.color }}">
										<i class="fa-solid fa-circle"></i>
									</span>
									{% if care.id == 2 or care.id == 5 %}
										{% for child in childs %}
											{% if child.id == appointment.childId %}
												<span>{{ care.name }}</span>
												<span class="appointment-child">pour
													{{ child.firstname }}
												</span>
											{% endif %}
										{% endfor %}
									{% else %}
										<span>{{ care.name }}</span>
									{% endif %}
								{% endif %}
							{% endfor %}
							<strong>
								<span>{{ appointment.date|dayName }}</span>
								<span>{{ appointment.date|date('d') }}</span>
								<span>{{ appointment.date|monthName }}</span>
								<span>{{ appointment.date|date('Y') }}</span>
								à
								<span>{{ appointment.date|date('H') }}</span>h<span>{{ appointment.date|date('i') }}</span>
							</strong>
						</li>
					{% else %}
						<li>
							<div class="profile_list_appointment_care empty_list">
								<span>Vous n'avez pas de rendez-vous</span>
							</div>
						</li>
					{% endfor %}
				</ul>
				<div class="pagination_profile">
					{{knp_pagination_render(pagination)}}
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/profile/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre profil
{% endblock %}

{% block stylesheets %}{# {{ parent() }} #}
	{# <link rel="stylesheet" href="{{ asset('/assets/css/pages/profile.css') }}"> #}
{% endblock %}

{% block body %}
	<div class="container">
		<div class="content content_profile">
			<h2>Votre profil</h2>
			<table class="edition_profile">
				<tbody>
					<tr>
						<td>Nom</td>
						<td>{{ user.firstname }}</td>
					</tr>
					<tr>
						<td>Prénom</td>
						<td>{{ user.lastname }}</td>
					</tr>
					<tr>
						<td>Email</td>
						<td>{{ user.email }}</td>
					</tr>
					<tr>
						<td>Adresse</td>
						<td>{{ user.address }}</td>
					</tr>
					<tr>
						<td>Code postal</td>
						<td>{{ user.zipcode }}</td>
					</tr>
					<tr>
						<td>Ville</td>
						<td>{{ user.city }}</td>
					</tr>
					<tr>
						<td>Téléphone fixe</td>
						<td>{{ user.homePhone|phone }}</td>
					</tr>
					<tr>
						<td>Téléphone portable</td>
						<td>{{ user.cellPhone|phone }}</td>
					</tr>
					<tr>
						<td>Date de naissance</td>
						<td>{{ user.birthday|date("d/m/Y") }}</td>
					</tr>
					<tr>
						<td>Mot de passe</td>
						<td>
							<a href="{{ path('profile_changePassword')}}">Changer le mot de passe</a>
						</td>
					</tr>
				</tbody>
			</table>
			<div class="edition_profile_action">
				<a href="{{ path('profile_edit') }}" class="btn btn-primary">Modifier votre profil</a>
			</div>
			{# Je teste le tableau childs pour savoir si l'utilisateur à déjà des enfants #}
			{% if childs %}
				<h2>Enfant(s)</h2>
				<table class="table_childs">
					<thead>
						<tr>
							<th>Prénom</th>
							<th>Date de naissance</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						{% for child in childs %}
							<tr>
								<td>{{ child.firstname }}</td>
								<td>{{ child.birthday|date("d/m/Y") }}</td>
								<td>
									<a href="{{ path('app_users_edit' , {id: child.id}) }}">
										<i class="fa-regular fa-pen-to-square"></i>
									</a>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
				<div class="edition_profile_action">
					<a href="{{ path('app_users_new') }}" class="btn btn-primary">Ajouter un enfant</a>
				</div>
			{% else %}
				<h2>Enfant</h2>
				<p>Vous n'avez pas encore d'enfant, ajoutez-en un pour pouvoir réserver une séance.</p>
				<div class="edition_profile_action">
					<a href="{{ path('app_users_new') }}" class="btn btn-primary">Ajouter un enfant</a>
				</div>
			{% endif %}
		</div>
	</div>
{% endblock %}